/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package rankingInicial;

import com.zetcode.Tetris;

import java.awt.*;

import com.zetcode.Tetris;
import rankingPorNivel.rankingPorNivel;
import rankingAbsoluto.rankingAbsoluto;

/**
 *
 * @author andreea
 */
public class rankingInicial extends javax.swing.JFrame {

    private rankingPorNivel pornivel = new rankingPorNivel();
    private rankingAbsoluto absoluto = new rankingAbsoluto();
    /**
     * Creates new form rankingInicial
     */
    public rankingInicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        background = new javax.swing.JPanel();
        absolutoButton = new javax.swing.JPanel();
        absolutoWord = new javax.swing.JLabel();
        porNivelButton = new javax.swing.JPanel();
        porNivelWord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        background.setBackground(new java.awt.Color(204, 204, 255));
        background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        absolutoButton.setBackground(new java.awt.Color(30, 144, 255));
        absolutoButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        absolutoButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        absolutoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                absolutoButtonMouseClicked(evt);
            }
        });
        absolutoButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        absolutoWord.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        absolutoWord.setForeground(new java.awt.Color(255, 255, 255));
        absolutoWord.setText("RANKING ABSOLUTO");
        absolutoWord.setName("NUEVA PARTIDA"); // NOI18N
        absolutoButton.add(absolutoWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 30));

        background.add(absolutoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 310, 50));

        porNivelButton.setBackground(new java.awt.Color(204, 0, 51));
        porNivelButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        porNivelButton.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        porNivelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                porNivelButtonMouseClicked(evt);
            }
        });
        porNivelButton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        porNivelWord.setFont(new java.awt.Font("Liberation Sans", 1, 24)); // NOI18N
        porNivelWord.setForeground(new java.awt.Color(255, 255, 255));
        porNivelWord.setText("RANKING POR NIVELES");
        porNivelWord.setName("NUEVA PARTIDA"); // NOI18N
        porNivelButton.add(porNivelWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 30));

        background.add(porNivelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 310, 50));

        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 120));

        pack();
    }// </editor-fold>

    private void porNivelButtonMouseClicked(java.awt.event.MouseEvent evt) {
        //javax.swing.JOptionPane.showMessageDialog(this, "Redirección a IU Ranking Por Nivel.");
        pornivel.setVisible(true);
        this.dispose();
    }

    private void absolutoButtonMouseClicked(java.awt.event.MouseEvent evt) {
        //javax.swing.JOptionPane.showMessageDialog(this, "Redirección a IU Ranking Absoluto.");
        absoluto.setVisible(true);
        this.dispose();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rankingInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rankingInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rankingInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rankingInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rankingInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JPanel absolutoButton;
    private javax.swing.JLabel absolutoWord;
    private javax.swing.JPanel background;
    private javax.swing.JPanel porNivelButton;
    private javax.swing.JLabel porNivelWord;
    // End of variables declaration

}
